name = "Symbiote vs Spore"
author = "233zsq"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdb1e940d26602ccb32b7bc65367ef97854c194d0a70f58766cb0b5067522c7"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
