name = "Symbiote vs Spore"
author = "233zsq"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "820fd675800dcf2d8ccfdffa9400db647c169c8f1002562511a79927ecfd23c0"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
